apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login-microservice
  template:
    metadata:
      labels:
        app: login-microservice
    spec:
      containers:
      - name: login-microservice
        image: devrg2025.azurecr.io/login-microservice:latest
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "250m" 
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: secret-82

