apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-microservice
spec:
  selector:
    matchLabels:
      app: login-microservice
  template:
    metadata:
      labels:
        app: login-microservice
    spec:
      containers:
      - name: login-microservice
        image: devrg2025.azurecr.io/login-microservice:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        imagePullSecrets:
      - name: secret-82
